### ISSUE TITLE
[bug]  plt.series assignment exception

### ISSUE THREAD

**Issue by WheatMaThink** [epi2me-labs/ezcharts#2]
Hi
please see 

`
plt = Plot()
plt.series = [dict(type='line')]  # OK

#### The following running errors :  value is not a valid dict (type=type_error.dict)

aList = [1, 2, 3, 4, 5]
plt.series = [dict(type='line', data=aList)]

spec = {
    'type': "line",
    'xAxisIndex': 0,
    'yAxisIndex': 0,
    'data': aList
}
plt.add_series(spec)

print(plt.to_json())
`

**Comment by cjw85** [comment]
Hi @WheatMaThink,

Thank you for your interest in ezCharts. The project is still very much in an experimental phase. Can you provide the full traceback for the error you see so we can better understand what has happened? The type definitions of eChart option objects has been automatically generated from the eCharts documentation source and is a little rough around the edges.

**Comment by WheatMaThink** [comment]
@cjw85 thank you for your reply
This is a very promising project

os system: macos 
python version : 3.9
ezcharts version : 0.2.2

一. question：run this code, you can reproduce. 

from ezcharts.plots import Plot
plt = Plot()
aList = [1, 2, 3, 4, 5]
plt.series = [dict(type='line', data=aList)]


二. exception information：
 plt.series = [dict(type='line', data=aList)]
  File "pydantic/main.py", line 385, in pydantic.main.BaseModel.__setattr__
pydantic.error_wrappers.ValidationError: 107 validation errors for Plot
series -> 0 -> data -> 0
  value is not a valid dict (type=type_error.dict)
series -> 0 -> data -> 1
  value is not a valid dict (type=type_error.dict)
series -> 0 -> data -> 2
  value is not a valid dict (type=type_error.dict)
...

**Comment by WheatMaThink** [comment]
data: Optional[List[Datum8]] = Field(

Modify as follows
   data: Optional[Union[List[float], List[Datum8]]] = Field(
