### ISSUE TITLE
pysam dependency

### ISSUE THREAD

**Issue by apwebber** [epi2me-labs/ezcharts#3]
upon running `pip install ezcharts` on windows, the installation fails due to not being able to build pysam.

[This topic](https://stackoverflow.com/questions/60197890/why-does-installing-pysam-python-package-fail) suggests that pysam is not currently installable on windows. Pysam is described as

>pysam — a Python package for reading, manipulating, and writing genomic data sets.

This seems like quite niche functionality.

I have installed ezcharts bypassing the pysam requirements and have run examples without issue.

Would it be possible to make pysam an optional dependency?

Thanks.

**Comment by cjw85** [comment]
> This seems like quite niche functionality.

On the contrary given where the package is developed, its quite a common dependency 😄 .

If your interest in `ezcharts` is in it being a Python API to eCharts, I should warn you that we have all but given up with eCharts (for a variety of reasons) so likely will deprecate the interface at some point in the future.

**Comment by apwebber** [comment]
Yeah I guessed as much.

That's a shame about deprecating it, as your interface is far more intuitive and tidy than pyecharts. I may consider forking it and keeping it alive but not sure I have the time.
